version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=aslon
      - MYSQL_PASSWORD=aslon
      - MYSQL_DATABASE=reservations
      