version: '3.1'

services:
  
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=aslon
      - MYSQL_PASSWORD=aslon
      - MYSQL_DATABASE=reservations
  # backend:
  #   build: 
  #     context: .
  #   container_name: backend
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - GIN_MODE=release
  #   depends_on:
  #     - "db"
  #   links:
  #     - "db:database"


      